// LISA: Built-In Water Sample Scenarios Dataset
// Comprehensive test & demonstration scenarios with realistic physics,
// strict ground-truth metadata, and documented expected behaviors.

import { SampleScenario } from './types';
import { SOURCE_VISUALS } from './sourceVisuals';

const STANDARD_OPTICAL_SETUP = {
  cuvettePathLengthCm: 1.0,
  dispersionElement: '1000 lines/mm holographic transmission grating',
  lightSource: 'High-CRI phosphor white LED',
  detector: 'Smartphone CMOS (400-700 nm, 2nm binning, 151 channels)',
};

export const SAMPLE_SCENARIOS: SampleScenario[] = [
  {
    id: 'scen-tap-water',
    name: 'Municipal Tap Water (Ashoka Cooler)',
    sourceType: 'Municipal Supply',
    category: 'drinking',
    description: 'Clean piped drinking water from Ashoka campus cooler. Negligible turbidity, minimal natural background phosphate from treatment additives.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Synthetic optical simulation derived from EPA 365.3 standard curve with low background noise (0.015). Not an experimental sample.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.tap_water,
    groundTruth: {
      concentration: 0.03,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.03,
      noiseLevel: 0.015,
      illuminationDrift: 0.005,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.005,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-TAP-001',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'SAFE',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.04,
      maxRelativeErrorPercent: 120, // Low-level limit of detection regime (LOD ~0.05 mg/L)
      origin: 'EPA Method 365.3 baseline noise floor near method detection limit.',
    },
    notes: 'Typical drinking water baseline. Should easily pass all 5 QC tiers and verify as SAFE (<0.10 mg P/L).',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-borewell-water',
    name: 'Borewell / Deep Aquifer Groundwater',
    sourceType: 'Groundwater',
    category: 'groundwater',
    description: 'Extracted from 120m rural borewell pump in Haryana. High dissolved mineral ions, mild natural background orthophosphate.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulated from hydrochemical survey parameters with moderate detector noise and slight optical alignment drift.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.borewell_water,
    groundTruth: {
      concentration: 0.08,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.08,
      noiseLevel: 0.018,
      illuminationDrift: -0.01,
      shiftPx: 1,
      isSaturated: false,
      turbidityAU: 0.02,
      colorInterferenceAU: 0.01,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-WELL-002',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'SAFE',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.04,
      maxRelativeErrorPercent: 40,
      origin: 'Field groundwater baseline tolerance at sub-0.1 mg/L concentration.',
    },
    notes: 'Slightly higher mineral baseline than municipal tap, but well under WHO eutrophication trigger threshold.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-village-pond',
    name: 'Eutrophic Village Pond',
    sourceType: 'Stagnant Surface Water',
    category: 'surface',
    description: 'Stagnant village pond receiving non-point agricultural runoff. Early-stage cyanobacterial bloom potential with elevated phosphorus.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulated optical transmission of molybdenum blue complex prepared from eutrophic pond surface sample.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.pond_water,
    groundTruth: {
      concentration: 0.45,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.45,
      noiseLevel: 0.02,
      illuminationDrift: 0.015,
      shiftPx: -1,
      isSaturated: false,
      turbidityAU: 0.05,
      colorInterferenceAU: 0.02,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-POND-003',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.05,
      maxRelativeErrorPercent: 12,
      origin: 'Empirical leave-one-concentration-out CV error (RMSE 0.048 mg/L) across 21 standards.',
    },
    notes: 'Exceeds surface water eutrophication threshold (>0.10 mg P/L). Triggers ALERT status.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-stormwater-drain',
    name: 'Sonipat Stormwater / Urban Drain',
    sourceType: 'Urban Runoff',
    category: 'effluent',
    description: 'Open municipal drainage canal carrying urban runoff and detergent residue. Significant dissolved phosphorus builder compounds.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulated urban runoff profile with moderate matrix scattering and strong molybdenum blue absorbance at 680 nm.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.drain_runoff,
    groundTruth: {
      concentration: 0.65,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.65,
      noiseLevel: 0.022,
      illuminationDrift: -0.02,
      shiftPx: 2,
      isSaturated: false,
      turbidityAU: 0.06,
      colorInterferenceAU: 0.03,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-DRAIN-004',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.06,
      maxRelativeErrorPercent: 10,
      origin: 'High-concentration calibration linear manifold error tolerance.',
    },
    notes: 'Demonstrates robust detection of urban greywater and non-point sewer overflow contamination.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-ag-runoff',
    name: 'Agricultural Fertilizer Runoff (DAP Spiked)',
    sourceType: 'Agricultural Drainage',
    category: 'agricultural',
    description: 'Furrow discharge water from wheat fields freshly fertilized with Diammonium Phosphate (DAP). High orthophosphate.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Primary live demonstration scenario matching Vial Y benchmark (0.40 mg P/L DAP reference standard).',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.ag_runoff,
    groundTruth: {
      concentration: 0.40,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.40,
      noiseLevel: 0.018,
      illuminationDrift: -0.01,
      shiftPx: 1,
      isSaturated: false,
      turbidityAU: 0.02,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-AGR-005',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.03,
      maxRelativeErrorPercent: 7.5,
      origin: 'Rigorous hackathon benchmark criterion: <7.5% relative error on 0.40 mg P/L standard.',
    },
    notes: 'Golden test benchmark. Engine must predict ~0.39-0.41 mg P/L with <5% error and PASS on all QC checks.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-rainwater-tank',
    name: 'Rooftop Rainwater Catchment Tank',
    sourceType: 'Rainwater',
    category: 'drinking',
    description: 'Clean roof-collected rainwater harvested in polyethylene storage tank. Pristine clarity, zero agricultural contact.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Synthetic optical simulation of ultra-pure catchment water (0.01 mg P/L baseline).',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.rainwater,
    groundTruth: {
      concentration: 0.01,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.01,
      noiseLevel: 0.012,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.002,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-RAIN-006',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'SAFE',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.04,
      maxRelativeErrorPercent: 200,
      origin: 'Detection limit regime (<0.03 mg P/L); absolute error bound ensures no false alarm.',
    },
    notes: 'Demonstrates absence of false alarms on pristine environmental waters.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-ro-water',
    name: 'Reverse Osmosis (RO) Laboratory Permeate',
    sourceType: 'Laboratory Purified',
    category: 'drinking',
    description: 'Deionized laboratory water passed through thin-film composite polyamide membrane. Zero-analyte reagent blank standard.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Synthetic representation of ideal 0.00 mg P/L reagent blank.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.ro_water,
    groundTruth: {
      concentration: 0.005,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.005,
      noiseLevel: 0.014,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-RO-007',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'SAFE',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.03,
      maxRelativeErrorPercent: 100,
      origin: 'Zero-blank offset stability criterion (<=0.03 mg P/L false positive floor).',
    },
    notes: 'Essential instrument trace baseline verification test for membrane permeate.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-turbid-surface',
    name: 'Turbid River Water (Colloidal Clay Suspension)',
    sourceType: 'Turbid Surface Water',
    category: 'surface',
    description: 'Monsoon river sample heavily laden with sub-micron suspended clay particles producing strong Mie wavelength-dependent scattering (~λ⁻¹).',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulation incorporating 0.38 AU scattering baseline with 0.15 AU organic matrix color tint.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.turbid_water,
    groundTruth: {
      concentration: 0.35,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.35,
      noiseLevel: 0.025,
      illuminationDrift: 0.0,
      shiftPx: 2,
      isSaturated: false,
      turbidityAU: 0.38,
      colorInterferenceAU: 0.15,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-TURB-008',
    },
    expected: {
      qc: 'PASS', // baseline correction compensates, or raises warning
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.22,
      maxRelativeErrorPercent: 65,
      origin: 'Uncompensated Mie scattering and humic acid yellowing attenuate net molybdenum blue peak recovery.',
    },
    notes: 'Tests LISA baseline subtraction (A_corr = A_meas - A_offset) in the presence of suspended particulates.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-unknown-dye',
    name: 'Unknown Chemistry: Food Dye Contaminant (Tartrazine)',
    sourceType: 'Adversarial Contaminant',
    category: 'adversarial',
    description: 'Yellow/green beverage dye spill in drain. Strong absorption at 426 nm, completely zero at 680 nm. NOT molybdenum blue.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Adversarial spectral anomaly designed to stress test Out-Of-Distribution (OOD) Mahalanobis distance manifold.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.unknown_dye,
    groundTruth: {
      concentration: 0.00,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'anomaly',
      concentration: 0.40,
      noiseLevel: 0.015,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-DYE-009',
    },
    expected: {
      qc: 'WARNING',
      ood: 'OUT_OF_DISTRIBUTION',
      shouldReject: true,
      expectedVerdict: 'REJECTED',
      rejectionReasonContains: 'Sample optical signature is outside the validated calibration manifold',
    },
    notes: 'CRITICAL SCIENTIFIC SAFETY: LISA must refuse to report a phosphate concentration when presented with alien chemistry.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-saturated-sensor',
    name: 'Hardware Fault: Saturated Sensor Overexposure',
    sourceType: 'Optical Hardware Fault',
    category: 'hardware_fault',
    description: 'Operator inadvertently set camera exposure time to 80ms instead of 10ms. Well capacity exceeded; pixels clipped at 255.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulation with isSaturated: true causing photodiode ADC clipping at 255 ceiling.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.saturated_sample,
    groundTruth: {
      concentration: 0.20,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.20,
      noiseLevel: 0.01,
      illuminationDrift: 0.3,
      shiftPx: 0,
      isSaturated: true,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-SAT-010',
    },
    expected: {
      qc: 'FAIL',
      ood: 'IN_DISTRIBUTION',
      shouldReject: true,
      expectedVerdict: 'REJECTED',
      rejectionReasonContains: 'Sensor pixel saturation detected',
    },
    notes: 'QC Tier 1 (Saturation Check) must intercept and reject before mathematical absorbance calculation is corrupted.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-misaligned-cuvette',
    name: 'Hardware Fault: Mechanical Slit Misalignment (+8px)',
    sourceType: 'Mechanical Fault',
    category: 'hardware_fault',
    description: '3D printed cuvette slot jammed with debris, translating optical axis by +8 pixels (approx +16 nm shift on 2nm/px dispersion).',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulation applying shiftPx: 8 exceeding registration tolerance threshold (+-6px).',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.misaligned_sample,
    groundTruth: {
      concentration: 0.40,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.40,
      noiseLevel: 0.015,
      illuminationDrift: 0.0,
      shiftPx: 8,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-MIS-011',
    },
    expected: {
      qc: 'FAIL',
      ood: 'IN_DISTRIBUTION',
      shouldReject: true,
      expectedVerdict: 'REJECTED',
      rejectionReasonContains: 'Cuvette mechanically displaced beyond registration tolerance',
    },
    notes: 'QC Tier 3 (Cross-correlation alignment check) detects shift > 6px and aborts.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-industrial-overrange',
    name: 'Industrial Effluent (>1.8 mg/L Out of Range)',
    sourceType: 'Industrial Discharge',
    category: 'effluent',
    description: 'Raw chemical plant discharge containing 1.85 mg P/L phosphate. Far above validated calibration upper bound (1.00 mg P/L).',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulation of high-optical density sample outside validated linear dynamic range.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.industrial_effluent,
    groundTruth: {
      concentration: 1.85,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 1.85,
      noiseLevel: 0.02,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.05,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-OVR-012',
    },
    expected: {
      qc: 'FAIL',
      ood: 'IN_DISTRIBUTION',
      shouldReject: true,
      expectedVerdict: 'ALERT',
      rejectionReasonContains: 'Sample exceeds validated dynamic range',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.35,
      maxRelativeErrorPercent: 20,
      origin: 'Extrapolation regime outside calibration envelope (0.00 - 1.00 mg P/L). Dilution 1:10 mandated.',
    },
    notes: 'Triggers automated prompt advising operator to perform 1:10 dilution with distilled water.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-uncalibrated-metal',
    name: 'Uncalibrated Metal: Iron (Fe²⁺ Phenanthroline Complex)',
    sourceType: 'Unsupported Heavy Metal',
    category: 'adversarial',
    description: 'Industrial effluent containing 0.50 mg Fe/L as iron phenanthroline complex (peak 510 nm). LISA has no validated iron calibration.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Analyte dispatch test: simulates uncalibrated iron chemistry requested against instrument.',
    analyteId: 'iron',
    sourceVisual: SOURCE_VISUALS.uncalibrated_metal,
    groundTruth: {
      concentration: 0.50,
      unit: 'mg Fe/L',
    },
    simulation: {
      analyte: 'iron',
      concentration: 0.50,
      noiseLevel: 0.015,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-IRON-013',
    },
    expected: {
      qc: 'FAIL',
      ood: 'OUT_OF_DISTRIBUTION',
      shouldReject: true,
      expectedVerdict: 'REJECTED',
      rejectionReasonContains: 'currently uncalibrated',
    },
    notes: 'BUG-001 Verification: instrument orchestrator must strictly refuse uncalibrated analyte inference.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-lead-reference',
    name: 'Lead Reference Standard (0.40 mg Pb/L)',
    sourceType: 'Simulated Heavy Metal Standard',
    category: 'effluent',
    description: 'Simulated clean lead-dithizone standard at 0.400 mg Pb/L (520 nm peak). Evaluates full simulated pipeline accuracy.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Controlled physics simulation: A(520 nm) ≈ 0.132 AU with 0.015 detector noise.',
    analyteId: 'lead',
    sourceVisual: SOURCE_VISUALS.lead_standard,
    groundTruth: {
      concentration: 0.40,
      unit: 'mg Pb/L',
    },
    simulation: {
      analyte: 'lead',
      concentration: 0.40,
      noiseLevel: 0.015,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-LEAD-REF-040',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.03,
      maxRelativeErrorPercent: 7.5,
      origin: 'Simulated Ridge grouped CV RMSE (0.013 mg/L) across 151 features.',
    },
    notes: 'Core 0.400 mg Pb/L verification standard.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-lead-trace',
    name: 'Lead Drinking Water Reference Limit (0.01 mg Pb/L)',
    sourceType: 'Simulated Drinking Water (Trace Metal)',
    category: 'drinking',
    description: 'Simulated potable water at the BIS IS 10500 regulatory limit (0.010 mg Pb/L). Resolves near optical LOD.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Near-noise optical signal (ΔA ≈ 0.0033 AU). Tests that engine reports trace warning without false confidence.',
    analyteId: 'lead',
    sourceVisual: SOURCE_VISUALS.lead_standard,
    groundTruth: {
      concentration: 0.01,
      unit: 'mg Pb/L',
    },
    simulation: {
      analyte: 'lead',
      concentration: 0.01,
      noiseLevel: 0.015,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-LEAD-TRACE-001',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'SAFE',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.02,
      maxRelativeErrorPercent: 150,
      origin: 'Near LOD baseline uncertainty regime.',
    },
    notes: 'IS 10500 reference limit test case.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-lead-low',
    name: 'Lead Elevated Water (0.10 mg Pb/L)',
    sourceType: 'Simulated Groundwater Contamination',
    category: 'groundwater',
    description: 'Simulated contaminated borehole with 0.10 mg Pb/L. Clear absorption peak at 520 nm above noise floor.',
    provenance: 'SIMULATED',
    provenanceDetails: '10x above IS 10500 limit. Clearly quantifiable optical response.',
    analyteId: 'lead',
    sourceVisual: SOURCE_VISUALS.lead_standard,
    groundTruth: {
      concentration: 0.10,
      unit: 'mg Pb/L',
    },
    simulation: {
      analyte: 'lead',
      concentration: 0.10,
      noiseLevel: 0.015,
      illuminationDrift: 0.005,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-LEAD-LOW-010',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.025,
      maxRelativeErrorPercent: 20,
      origin: 'Simulated Ridge linear regime.',
    },
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-lead-high',
    name: 'Lead Industrial Battery Effluent (1.50 mg Pb/L)',
    sourceType: 'Simulated Industrial Discharge',
    category: 'effluent',
    description: 'High-range industrial battery discharge (1.50 mg Pb/L). Strong pink chromophore optical density.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Upper dynamic range test: A(520 nm) ≈ 0.495 AU.',
    analyteId: 'lead',
    sourceVisual: SOURCE_VISUALS.lead_standard,
    groundTruth: {
      concentration: 1.50,
      unit: 'mg Pb/L',
    },
    simulation: {
      analyte: 'lead',
      concentration: 1.50,
      noiseLevel: 0.02,
      illuminationDrift: -0.01,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.02,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-LEAD-HIGH-150',
    },
    expected: {
      qc: 'PASS',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.12,
      maxRelativeErrorPercent: 8.0,
      origin: 'High concentration upper dynamic range simulation tolerance.',
    },
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-lead-interference',
    name: 'Lead with Turbidity Interference (0.40 mg Pb/L + Turbidity)',
    sourceType: 'Simulated Turbid Industrial Runoff',
    category: 'surface',
    description: '0.40 mg Pb/L lead spiked into water with 0.35 AU colloidal turbidity. QC triggers turbidity advisory.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Evaluates baseline correction and QC turbidity detection in lead mode.',
    analyteId: 'lead',
    sourceVisual: SOURCE_VISUALS.turbid_water,
    groundTruth: {
      concentration: 0.40,
      unit: 'mg Pb/L',
    },
    simulation: {
      analyte: 'lead',
      concentration: 0.40,
      noiseLevel: 0.02,
      illuminationDrift: 0.0,
      shiftPx: 1,
      isSaturated: false,
      turbidityAU: 0.35,
      colorInterferenceAU: 0.05,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-LEAD-TURB-040',
    },
    expected: {
      qc: 'WARNING',
      ood: 'IN_DISTRIBUTION',
      shouldReject: false,
      expectedVerdict: 'ALERT',
    },
    tolerance: {
      maxAbsoluteErrorMgL: 0.08,
      maxRelativeErrorPercent: 20,
      origin: 'Turbidity baseline correction offset.',
    },
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-lead-unknown',
    name: 'Adversarial Dye in Lead Mode (Tartrazine Yellow 426 nm)',
    sourceType: 'Synthetic Dye Contaminant',
    category: 'adversarial',
    description: 'Yellow food dye (Tartrazine 426 nm) tested as Lead. Spectral shape does not match 520 nm dithizone manifold.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Analyte-specific OOD test: Tartrazine has no 520 nm peak; Lead manifold must reject.',
    analyteId: 'lead',
    sourceVisual: SOURCE_VISUALS.unknown_dye,
    groundTruth: {
      concentration: 0.0,
      unit: 'mg Pb/L',
    },
    simulation: {
      analyte: 'anomaly',
      concentration: 1.0,
      noiseLevel: 0.02,
      illuminationDrift: 0.0,
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-LEAD-DYE-OOD',
    },
    expected: {
      qc: 'WARNING',
      ood: 'OUT_OF_DISTRIBUTION',
      shouldReject: true,
      expectedVerdict: 'REJECTED',
      rejectionReasonContains: 'outside the validated Lead (Heavy Metal) calibration manifold',
    },
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
  {
    id: 'scen-dim-light',
    name: 'Hardware Fault: Degraded Optical Flux (Low Light)',
    sourceType: 'Optical Hardware Fault',
    category: 'hardware_fault',
    description: 'Dying 3V coin cell battery in illuminator drops LED output by 90%. Signal falls into detector read noise.',
    provenance: 'SIMULATED',
    provenanceDetails: 'Simulation with severe negative illumination drift (-0.90) reducing blank throughput below 30 AU threshold.',
    analyteId: 'phosphate',
    sourceVisual: SOURCE_VISUALS.dim_light,
    groundTruth: {
      concentration: 0.40,
      unit: 'mg P/L',
    },
    simulation: {
      analyte: 'phosphate',
      concentration: 0.40,
      noiseLevel: 0.03,
      illuminationDrift: -0.90, // Severe drop triggering Peak < 30 AU
      shiftPx: 0,
      isSaturated: false,
      turbidityAU: 0.0,
      colorInterferenceAU: 0.0,
      deviceProfileId: 'device-a-reference',
      seed: 'LISA-SCEN-DIM-014',
    },
    expected: {
      qc: 'FAIL',
      ood: 'IN_DISTRIBUTION',
      shouldReject: true,
      expectedVerdict: 'REJECTED',
      rejectionReasonContains: 'Optical transmission too dark',
    },
    notes: 'QC Tier 2 (Signal Throughput Check) must reject due to photon starvation.',
    opticalContext: STANDARD_OPTICAL_SETUP,
  },
];
