// LISA: Measurement history
// A scannable log, not a data table. Each row leads with the number, because
// that is what someone re-opening the log is looking for.

import React, { useState } from 'react';
import { Download, Trash2, Share2, FileText, Check, History as HistoryIcon } from 'lucide-react';
import { MeasurementRecord, VerdictStatus } from '../types';
import { Modal } from './ui/Modal';
import { Segmented } from './ui/Segmented';
import { QC_TONE, QC_WORD, StatusPill } from './ui/Status';

interface HistoryDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  records: MeasurementRecord[];
  onSelectRecord: (record: MeasurementRecord) => void;
  onClearHistory: () => void;
}

type Filter = 'ALL' | VerdictStatus;

const FILTERS: { value: Filter; label: string }[] = [
  { value: 'ALL', label: 'All' },
  { value: 'SAFE', label: 'Safe' },
  { value: 'CAUTION', label: 'Caution' },
  { value: 'ALERT', label: 'Alert' },
  { value: 'REJECTED', label: 'Rejected' },
];

function formatWhen(timestamp: string): string {
  const date = new Date(timestamp);
  const time = date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  const startOfDay = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
  const days = Math.round((startOfDay(new Date()) - startOfDay(date)) / 86_400_000);

  if (days === 0) return `Today, ${time}`;
  if (days === 1) return `Yesterday, ${time}`;
  return `${date.toLocaleDateString([], { day: 'numeric', month: 'short' })}, ${time}`;
}

export const HistoryDrawer: React.FC<HistoryDrawerProps> = ({
  isOpen,
  onClose,
  records,
  onSelectRecord,
  onClearHistory,
}) => {
  const [filter, setFilter] = useState<Filter>('ALL');
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [confirmClear, setConfirmClear] = useState(false);

  const filtered = filter === 'ALL' ? records : records.filter((r) => r.verdict === filter);

  const handleExportCSV = () => {
    if (records.length === 0) return;
    const headers = [
      'ID',
      'Timestamp',
      'Sample Name',
      'Analyte',
      'Analyte ID',
      'Concentration',
      'Unit',
      'Uncertainty',
      'Verdict',
      'QC Status',
      'OOD Status',
      'Model',
      'Device ID',
    ];
    const rows = records.map((r) => [
      r.id,
      r.timestamp,
      `"${r.sampleName}"`,
      r.analyteName,
      r.analyteId,
      r.concentration !== null ? r.concentration.toFixed(3) : 'REJECTED',
      r.unit,
      r.uncertainty !== null ? r.uncertainty.toFixed(3) : 'N/A',
      r.verdict,
      r.qcStatus,
      r.oodStatus,
      r.selectedModel,
      r.deviceId,
    ]);

    const csvContent =
      'data:text/csv;charset=utf-8,' +
      [headers.join(','), ...rows.map((e) => e.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `lisa_water_log_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportJSON = () => {
    if (records.length === 0) return;
    const jsonStr = JSON.stringify(records, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `lisa_audit_trail_${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async (record: MeasurementRecord) => {
    const text = `💧 *LISA Water Quality Report*\n📅 ${new Date(
      record.timestamp
    ).toLocaleString()}\n📍 Sample: ${record.sampleName}\n🧪 Analyte: ${
      record.analyteName
    }\n📊 Concentration: ${
      record.concentration !== null
        ? `${record.concentration.toFixed(2)} ± ${record.uncertainty?.toFixed(2)} ${record.unit}`
        : 'REJECTED'
    }\n🚦 Status: *${record.verdict}*\n🛡️ QC: ${record.qcStatus} | OOD: ${
      record.oodStatus
    }\n🔬 Device: ${record.deviceId}\n_Generated by LISA Spectral Sensing_`;

    try {
      await navigator.clipboard.writeText(text);
      setCopiedId(record.id);
      window.setTimeout(() => setCopiedId((id) => (id === record.id ? null : id)), 2200);
    } catch {
      setCopiedId(null);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Measurement history"
      subtitle={
        records.length === 0
          ? 'No measurements logged yet.'
          : `${records.length} ${records.length === 1 ? 'record' : 'records'} in this session's audit trail.`
      }
      size="wide"
      headActions={
        <>
          <button
            type="button"
            className="btn btn--secondary btn--sm"
            onClick={handleExportCSV}
            disabled={records.length === 0}
          >
            <Download size={14} aria-hidden="true" />
            <span>CSV</span>
          </button>
          <button
            type="button"
            className="btn btn--secondary btn--sm"
            onClick={handleExportJSON}
            disabled={records.length === 0}
          >
            <FileText size={14} aria-hidden="true" />
            <span>JSON</span>
          </button>
          {confirmClear ? (
            <button
              type="button"
              className="btn btn--danger btn--sm"
              onClick={() => {
                onClearHistory();
                setConfirmClear(false);
              }}
            >
              <Trash2 size={14} aria-hidden="true" />
              <span>Confirm clear</span>
            </button>
          ) : (
            <button
              type="button"
              className="btn btn--ghost btn--icon"
              onClick={() => setConfirmClear(true)}
              disabled={records.length === 0}
              aria-label="Clear history"
              title="Clear history"
            >
              <Trash2 size={16} aria-hidden="true" />
            </button>
          )}
        </>
      }
    >
      {records.length === 0 ? (
        <div className="empty">
          <HistoryIcon className="empty__icon" size={22} aria-hidden="true" />
          <span className="empty__title">Nothing logged yet</span>
          <span className="empty__text">
            Every measurement you capture is written here with its full quality record.
          </span>
        </div>
      ) : (
        <>
          {records.length > 1 && (
            <Segmented<Filter>
              label="Filter by verdict"
              block
              value={filter}
              onChange={setFilter}
              options={FILTERS}
            />
          )}

          {filtered.length === 0 ? (
            <div className="empty">
              <span className="empty__text">No measurements with that verdict.</span>
            </div>
          ) : (
            <div
              style={{
                border: '1px solid var(--line)',
                borderRadius: 'var(--r-md)',
                overflow: 'hidden',
              }}
            >
              <div className="history-list">
                {filtered.map((r) => {
                  const isRejected = r.isRejected || r.verdict === 'REJECTED';
                  const copied = copiedId === r.id;

                  return (
                    <div className="history-item" key={r.id}>
                      <button
                        type="button"
                        onClick={() => {
                          onSelectRecord(r);
                          onClose();
                        }}
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: 14,
                          flex: 1,
                          minWidth: 0,
                          background: 'transparent',
                          border: 0,
                          padding: 0,
                          textAlign: 'left',
                          cursor: 'pointer',
                          color: 'inherit',
                        }}
                      >
                        <span
                          className={`history-item__value${
                            isRejected ? ' history-item__value--rejected' : ''
                          }`}
                        >
                          {isRejected ? (
                            'Rejected'
                          ) : (
                            <>
                              {r.concentration?.toFixed(2) ?? '—'}
                              <span className="history-item__unit">{r.unit}</span>
                            </>
                          )}
                        </span>

                        <span className="history-item__meta">
                          <span className="history-item__name">{r.sampleName}</span>
                          <span className="history-item__when">
                            {r.analyteName} · {formatWhen(r.timestamp)}
                          </span>
                        </span>

                        <StatusPill tone={QC_TONE[r.qcStatus]}>{QC_WORD[r.qcStatus]}</StatusPill>
                      </button>

                      <div className="history-item__actions">
                        <button
                          type="button"
                          className="btn btn--ghost btn--icon"
                          onClick={() => handleShare(r)}
                          aria-label={copied ? 'Report copied' : 'Copy report for sharing'}
                          title={copied ? 'Copied' : 'Copy report for sharing'}
                        >
                          {copied ? (
                            <Check size={16} className="icon-pass" aria-hidden="true" />
                          ) : (
                            <Share2 size={16} aria-hidden="true" />
                          )}
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </>
      )}
    </Modal>
  );
};
